spring:
  profiles:
    active: dev

--- 
spring:
  profiles: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/ad-data?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: kedacom
    password: kedacom
#    druid:
#      validation-query: select 1
logging:
  level: 
     com.kedacom.tz.sh: debug
    
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not-empty
      update-strategy: not-empty
      select-strategy: not-empty
      table-underline: true
#      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml
  type-handlers-package: com.kedacom.tz.sh.typeHandlers
  
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/ad-data?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: kedacom
    password: kedacom
      
    
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not-empty
      update-strategy: not-empty
      select-strategy: not-empty
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml
  type-handlers-package: com.kedacom.tz.sh.typeHandlers


---
spring:
  profiles: more
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://172.16.188.99:3306/ad-data?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: kedacom
      password: kedacom
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://172.16.188.16:3306/demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: ysl
      password: ysl
      

---
spring:
  profiles: master_slave
  datasource:
    druid:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.16.188.99:3306/ad-data?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
        username: kedacom
        password: kedacom
      slave1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.16.188.16:3306/demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
        username: ysl
        password: ysl
  